using System.Drawing.Imaging;

namespace pixel8r
{
    public static class GlobalVars
    {
        public static Color[] mesenColors = [
            Color.FromArgb(102, 102, 102),
            Color.FromArgb(0, 42, 136),
            Color.FromArgb(20, 18, 167),
            Color.FromArgb(59, 0, 164),
            Color.FromArgb(92, 0, 126),
            Color.FromArgb(110, 0, 64),
            Color.FromArgb(108, 6, 0),
            Color.FromArgb(86, 29, 0),
            Color.FromArgb(51, 53, 0),
            Color.FromArgb(11, 72, 0),
            Color.FromArgb(0, 82, 0),
            Color.FromArgb(0, 79, 8),
            Color.FromArgb(0, 64, 77),
            Color.FromArgb(0, 0, 0),
            Color.FromArgb(173, 173, 173),
            Color.FromArgb(21, 95, 217),
            Color.FromArgb(64, 64, 255),
            Color.FromArgb(117, 39, 254),
            Color.FromArgb(160, 26, 204),
            Color.FromArgb(183, 30, 123),
            Color.FromArgb(181, 49, 32),
            Color.FromArgb(153, 78, 0),
            Color.FromArgb(107, 109, 0),
            Color.FromArgb(56, 135, 0),
            Color.FromArgb(12, 147, 0),
            Color.FromArgb(0, 143, 50),
            Color.FromArgb(0, 124, 141),
            Color.FromArgb(255, 254, 255),
            Color.FromArgb(100, 176, 255),
            Color.FromArgb(146, 144, 255),
            Color.FromArgb(198, 118, 255),
            Color.FromArgb(243, 106, 255),
            Color.FromArgb(254, 110, 204),
            Color.FromArgb(254, 129, 112),
            Color.FromArgb(234, 158, 34),
            Color.FromArgb(188, 190, 0),
            Color.FromArgb(136, 216, 0),
            Color.FromArgb(92, 228, 48),
            Color.FromArgb(69, 224, 130),
            Color.FromArgb(75, 205, 222),
            Color.FromArgb(79, 79, 79),
            Color.FromArgb(255, 254, 255),
            Color.FromArgb(192, 223, 255),
            Color.FromArgb(211, 210, 255),
            Color.FromArgb(232, 200, 255),
            Color.FromArgb(215, 194, 255),
            Color.FromArgb(254, 196, 234),
            Color.FromArgb(254, 204, 197),
            Color.FromArgb(247, 216, 165),
            Color.FromArgb(228, 229, 148),
            Color.FromArgb(207, 239, 150),
            Color.FromArgb(189, 244, 171),
            Color.FromArgb(179, 243, 204),
            Color.FromArgb(181, 235, 242),
            Color.FromArgb(184, 184, 184),
        ];

        public static Color[] webColors = [
            Color.AliceBlue,
            Color.AntiqueWhite,
            Color.Aqua,
            Color.Aquamarine,
            Color.Azure,
            Color.Beige,
            Color.Bisque,
            Color.Black,
            Color.BlanchedAlmond,
            Color.Blue,
            Color.BlueViolet,
            Color.Brown,
            Color.BurlyWood,
            Color.CadetBlue,
            Color.Chartreuse,
            Color.Chocolate,
            Color.Coral,
            Color.CornflowerBlue,
            Color.Cornsilk,
            Color.Crimson,
            Color.Cyan,
            Color.DarkBlue,
            Color.DarkCyan,
            Color.DarkGoldenrod,
            Color.DarkGray,
            Color.DarkGreen,
            Color.DarkKhaki,
            Color.DarkMagenta,
            Color.DarkOliveGreen,
            Color.DarkOrange,
            Color.DarkOrchid,
            Color.DarkRed,
            Color.DarkSalmon,
            Color.DarkSeaGreen,
            Color.DarkSlateBlue,
            Color.DarkSlateGray,
            Color.DarkTurquoise,
            Color.DarkViolet,
            Color.DeepPink,
            Color.DeepSkyBlue,
            Color.DimGray,
            Color.DodgerBlue,
            Color.Firebrick,
            Color.FloralWhite,
            Color.ForestGreen,
            Color.Fuchsia,
            Color.Gainsboro,
            Color.GhostWhite,
            Color.Gold,
            Color.Goldenrod,
            Color.Gray,
            Color.Green,
            Color.GreenYellow,
            Color.Honeydew,
            Color.HotPink,
            Color.IndianRed,
            Color.Indigo,
            Color.Ivory,
            Color.Khaki,
            Color.Lavender,
            Color.LavenderBlush,
            Color.LawnGreen,
            Color.LemonChiffon,
            Color.LightBlue,
            Color.LightCoral,
            Color.LightCyan,
            Color.LightGoldenrodYellow,
            Color.LightGreen,
            Color.LightGray,
            Color.LightPink,
            Color.LightSalmon,
            Color.LightSeaGreen,
            Color.LightSkyBlue,
            Color.LightSlateGray,
            Color.LightSteelBlue,
            Color.LightYellow,
            Color.Lime,
            Color.LimeGreen,
            Color.Linen,
            Color.Magenta,
            Color.Maroon,
            Color.MediumAquamarine,
            Color.MediumBlue,
            Color.MediumOrchid,
            Color.MediumPurple,
            Color.MediumSeaGreen,
            Color.MediumSlateBlue,
            Color.MediumSpringGreen,
            Color.MediumTurquoise,
            Color.MediumVioletRed,
            Color.MidnightBlue,
            Color.MintCream,
            Color.MistyRose,
            Color.Moccasin,
            Color.NavajoWhite,
            Color.Navy,
            Color.OldLace,
            Color.Olive,
            Color.OliveDrab,
            Color.Orange,
            Color.OrangeRed,
            Color.Orchid,
            Color.PaleGoldenrod,
            Color.PaleGreen,
            Color.PaleTurquoise,
            Color.PaleVioletRed,
            Color.PapayaWhip,
            Color.PeachPuff,
            Color.Peru,
            Color.Pink,
            Color.Plum,
            Color.PowderBlue,
            Color.Purple,
            Color.RebeccaPurple,
            Color.Red,
            Color.RosyBrown,
            Color.RoyalBlue,
            Color.SaddleBrown,
            Color.Salmon,
            Color.SandyBrown,
            Color.SeaGreen,
            Color.SeaShell,
            Color.Sienna,
            Color.Silver,
            Color.SkyBlue,
            Color.SlateBlue,
            Color.SlateGray,
            Color.Snow,
            Color.SpringGreen,
            Color.SteelBlue,
            Color.Tan,
            Color.Teal,
            Color.Thistle,
            Color.Tomato,
            Color.Turquoise,
            Color.Violet,
            Color.Wheat,
            Color.White,
            Color.WhiteSmoke,
            Color.Yellow,
            Color.YellowGreen
];

        public static string FilePath { get; set; }
        public static int ImageWidth { get; set; }
        public static int ImageHeight { get; set; }

        public static Image PreviousImage { get; set; }

        public const int pictureBoxOffsetX = 255;
        public const int pictureBoxOffsetY = 33;
        public const int pictureBoxWidth = 1118;
        public const int pictureBoxHeight = 720;
        public const int pictureBoxCenterX = pictureBoxOffsetX + pictureBoxWidth / 2;
        public const int pictureBoxCenterY = pictureBoxOffsetY + pictureBoxHeight / 2;
    }
}
